### ISSUE TITLE
Disabling SSL Certificate Check

### ISSUE THREAD

**Issue by dragondgold** [libgit2/libgit2sharp#1290]
I was using this code to clone a repository:

```
var co = new CloneOptions();
 co.CredentialsProvider = (_url, _user, _cred) => new UsernamePasswordCredentials { Username = USERNAME, Password = PASSWORD };

Repository.Clone("https://github.com/user/repo.git", directory, co);
```

It was working great, but suddenly I'm starting to get this error when cloning:

```
LibGit2Sharp.LibGit2SharpException: user cancelled certificate check: 
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 160
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in c:\Git\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 328
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in c:\Git\libgit2sharp\LibGit2Sharp\Repository.cs:line 680
```

I have no idea why I'm getting this when it was working perfectly. So I tried to bypass it with:

```
co.CertificateCheck += delegate (Certificate certificate, bool valid, string host)
{
      return true;
};
```

It starts clonning but suddenly I get the exception again:

```
LibGit2Sharp.LibGit2SharpException: user cancelled certificate check: 
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 160
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage) in c:\Git\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2215
   at LibGit2Sharp.Network.DoFetch(FetchOptions options, RemoteSafeHandle remoteHandle, String logMessage, IEnumerable`1 refspecs) in c:\Git\libgit2sharp\LibGit2Sharp\Network.cs:line 218
   at LibGit2Sharp.Network.DoFetch(RepositorySafeHandle repoHandle, Remote remote, FetchOptions options, String logMessage, IEnumerable`1 refspecs) in c:\Git\libgit2sharp\LibGit2Sharp\Network.cs:line 164
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, String logMessage) in c:\Git\libgit2sharp\LibGit2Sharp\Network.cs:line 260
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options) in c:\Git\libgit2sharp\LibGit2Sharp\Network.cs:line 237
   at LibGit2Sharp.Network.Pull(Signature merger, PullOptions options) in c:\Git\libgit2sharp\LibGit2Sharp\Network.cs:line 566
```

Is this a `GitHub`, `git`, `libgit2sharp` or mine issue? Is there any way to completely disable SSL Certificate Check? Or any other way to solve this?

**Comment by ethomson** [comment]
LibGit2Sharp won't remember your `CertificateCheck` callback from the clone options when you do a pull.  You'll need to set the similar option in `PullOptions`.

This shouldn't be necessary, though, when talking to github.  Is your system's clock set to some totally off-the-wall value in the past or future?  Has your network administrator installed some fun new hardware on your egress?

Can you visit https://github.com/ in Internet Explorer successfully?

**Comment by dragondgold** [comment]
The system clock is set to today so should be ok. I'm testing on my personal computer so no, no hardware issues and I can also visit https://github.com/ from Internet Explorer.

After restarting the PC 2 times the problem solved itself, so this is not a `libgit2sharp` issue. Thank you for the information! I think you can close the issue now :)

**Comment by ethomson** [comment]
Odd!  Thanks for the update, I'll close this.  :)
