### ISSUE TITLE
Test CanExtractSignatureFromCommit fails in master branch

### ISSUE THREAD

**Issue by AArnott** [libgit2/libgit2sharp#1314]
This test fails in the master branch (as of 1fb7fc5b1d26c893e085c2782d5ee483d56c5a18)

```
Test Name:	LibGit2Sharp.Tests.CommitFixture.CanExtractSignatureFromCommit
Test FullName:	LibGit2Sharp.Tests.CommitFixture.CanExtractSignatureFromCommit
Test Source:	C:\Users\andarno\git\libgit2sharp\LibGit2Sharp.Tests\CommitFixture.cs : line 1114
Test Outcome:	Failed
Test Duration:	0:00:00.011

Result StackTrace:	
at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_object_lookup(RepositoryHandle repo, ObjectId id, GitObjectType type) in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 1448
   at LibGit2Sharp.Repository.LookupInternal(ObjectId id, GitObjectType type, FilePath knownPath) in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp\Repository.cs:line 534
   at LibGit2Sharp.Repository.Lookup(ObjectId id, ObjectType type) in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp\Repository.cs:line 516
   at LibGit2Sharp.RepositoryExtensions.Lookup[T](IRepository repository, ObjectId id) in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp\RepositoryExtensions.cs:line 51
   at LibGit2Sharp.Tests.CommitFixture.CanExtractSignatureFromCommit() in C:\Users\andarno\git\libgit2sharp\LibGit2Sharp.Tests\CommitFixture.cs:line 1122
Result Message:	LibGit2Sharp.LibGit2SharpException : Failed to parse bad commit object
```

**Comment by ethomson** [comment]
Fixed via #1315
