### ISSUE TITLE
repo.Network.Push is failing for large repository

### ISSUE THREAD

**Issue by nalinrajgupta** [libgit2/libgit2sharp#1324]
I did a clone of https://github.com/Microsoft/TypeScript repo (~250 MB ) locally. I was trying to push it to gihub using below code, but it keeps failing with error message **"No error message has been provided by the native library"**: I am successfully able to push a repository of size ~1MB with the same code.

**Code:**

var localPath = @"F:\temp\nalin\TypeScript";
            var repository = new Repository(localPath);
            var destination = repository.Network.Remotes["dest"];
            var options = new PushOptions();
            options.CredentialsProvider = (urs, user, cred) => new UsernamePasswordCredentials()
            {
                Username = "username",
                Password = "pass"
            };
            Console.WriteLine("Push Start..");
            repository.Network.Push(destination, @"refs/heads/master", options);
            Console.WriteLine("Push end !!");

**Error Stack Trace:**

  at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 160
   at LibGit2Sharp.Core.Proxy.git_remote_push(RemoteSafeHandle remote, IEnumerable`1 refSpecs, GitPushOptions opts) in c:\Git\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 2172
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs, PushOptions pushOptions) in c:\Git\libgit2sharp\LibGit2Sharp\Network.cs:line 534
   at LibGit2Sharp.Network.Push(Remote remote, String pushRefSpec, PushOptions pushOptions) in c:\Git\libgit2sharp\LibGit2Sharp\Network.cs:line 493
   at GitMirrorClone.Program.Main(String[] args) in C:\Users\nagup\Documents\Visual Studio 2015\Projects\GitMirrorClone\GitMirrorClone\Program.cs:line 44
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I am using libgit2Sharp 0.22. Is this a known issue ?

**Comment by ethomson** [comment]
No, this is not a known issue.  Does it work for smaller repositories?

What type of server is this?  What's the actual type of exception being thrown?  (A strongly typed exception may not need a message.)  What's wireshark/netmon/fiddler showing happened here?

**Comment by gauravsaraltest** [comment]
yes, it is working for smaller repositories.  (like repository of libgit2sharp) 
but even while pushing libgit2sharp repository the memory usage shoots up to nearly 1gb

we tried it in a scenario where we cloned repository from github and tried to push to github only
(attaching the exact code, after changing passwords)
[sample.txt](https://github.com/libgit2/libgit2sharp/files/293977/sample.txt)

exact exception is :
"An unhandled exception of type 'LibGit2Sharp.LibGit2SharpException' occurred in LibGit2Sharp.dll

Additional information: Out of memory"
I am not able to catch any fiddler trace for this.

**Comment by ethomson** [comment]
I see; this may have been fixed for some recent changes.  Can you try a prerelease and see if this still occurs?  https://www.nuget.org/packages/LibGit2Sharp/0.23.0-pre20150419160303

**Comment by gauravsaraltest** [comment]
Thanks @ethomson , it appears to be working with the latest pre-release
