### ISSUE TITLE
Leak when iterating through commits and diff them

### ISSUE THREAD

**Issue by Gentlehag** [libgit2/libgit2sharp#1359]
When I run the code below on a production repository, i can see that the memory is all the time increasing and after about 3000 commits my pc  crashes with out of memory.

For about 1000 commit it reserved about 500 MB Ram.

Code for Testsetup see here:
https://gist.github.com/Gentlehag/9f595ab13f459e22859fa5d9557e550b

**Comment by Gentlehag** [comment]
Btw I tried it with the current prerelease version this looks better with ram consumption. but there are a lot of debug outputs, and sometimes I see this error in the debug out:

Unexpected finalization of RepositoryHandle handle (af1c1cc0-41c4-4fc2-a056-1755345b4862)
   at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, RepositoryRequiredParameter requiredParameter) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:line 109
   at ConsoleApplication8.Program.Main(String[] args) in c:\users\boase\documents\visual studio 2015\Projects\ConsoleApplication8\ConsoleApplication8\Program.cs:line 17
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ied206** [comment]
Looking through git cli's memory usage with gecko-dev, it seems high memory usage with hugh repo is not a leak but limitation of git. Sorry for misleading report yesterday.

**Comment by ethomson** [comment]
Thanks for the reply @ied206, but I think this still bears some investigation.  There may be optimizations that we can make to ease your burden.
