### ISSUE TITLE
Repository.Clone throwing exceptions due "early EOF" and invalid hex digit in length

### ISSUE THREAD

**Issue by gjmveloso** [libgit2/libgit2sharp#1441]
I'm running into a completely new issue with LibGit2Sharp that seems to be particular to an specific repository. After a while performing the ``Repository.Clone()`` operation the library throws "early EOF" or "invalid hex digit in length: '.4.." "or invalid hex digit in length: '.L<'"' exceptions.

Currently using LibGit2Sharp v0.23.1 with NativeBinaries pointing to v1.0.164

Others repos targeting the same Git server worked just fine. 

Anyone here ran into similar issues in the past that can help me debug this further?

## early EOF exception
at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Proxy.cs:line 355
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:line 732
   at RepoChangesNotifications.GitManager.GetOrUpdateRepository() in C:\Code\repository-changes\RepoChangesNotifications\GitManager.cs:line 55``

## invalid hex digit in length exceptions
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Core\Proxy.cs:line 355
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in c:\Git\LibGit2Sharp-2\LibGit2Sharp\Repository.cs:line 732
   at RepoChangesNotifications.GitManager.GetOrUpdateRepository() in C:\Code\repository-changes\RepoChangesNotifications\GitManager.cs:line 55

Thanks,
Gustavo

**Comment by ethomson** [comment]
This sounds very much like a server error.

What software is the server running?

Is the server public?  Can I point a client at it and see the results?

Most importantly, can you clone with the command line git client?
