### ISSUE TITLE
"The server returned an invalid or unrecognized response" when clone repository larger than 2GB

### ISSUE THREAD

**Issue by AndreyVaskovskiy** [libgit2/libgit2sharp#1477]
Stack trace:
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in C:\projects\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 356
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in C:\projects\libgit2sharp\LibGit2Sharp\Repository.cs:line 732
   at GitTestLargeRepo.Program.Main(String[] args) in c:\users\vaskovskiy\documents\visual studio 2017\Projects\GitTestLargeRepo\GitTestLargeRepo\Program.cs:line 17

**Comment by AndreyVaskovskiy** [comment]
**libgit2** api method **git_clone** returns -1. The message "The server returned an invalid or unrecognized response" comes from **libgit2** api **giterr_last** method. The repository is more than 3GB. I can clone it from console without any errors. The **NGit.dll** also worked fine for me.

**Comment by ethomson** [comment]
Is your application running in 32 bit mode or 64 bit mode?

If you uncheck 'Prefer 32 bit' in your app's properties, does succeed?

**Comment by AndreyVaskovskiy** [comment]
I've unchecked the "Prefer 32-bit" checkbox for my application but the error is still the same.
+		$exception	{"failed to read data: The server returned an invalid or unrecognized response\r\n"}	LibGit2Sharp.LibGit2SharpException.

**Comment by AndreyVaskovskiy** [comment]
It takes about 10 minutes until the exception is thrown. I've created CloneOptions listeners for OnTransferProgress and OnProgress Handlers and none of them where called in this 10 minutes

**Comment by ethomson** [comment]
Can you provide any data here?

Are you behind a proxy?  Do you need to authenticate to said proxy?  What software is the server running?  If you use wireshark or fiddler, is the server sending any data?  Can you provide a trace of a successful clone with an unsuccessful one?

Can you point me to the repository in question?  That would be ideal.

**Comment by AndreyVaskovskiy** [comment]
I'm not behind the proxy. I use cloudforge.com to store the source code. It works fine with a small test repository but fails with the production repository. I can use fiddler but I could find a way to specify the proxy "http://127.0.0.1:8888" in LibGit2Sharp.

**Comment by ethomson** [comment]
Thanks for the info.  I'm going to touch base with CloudForge and test cloning a 3GB repository to see whether this also fails for me.  Then we can continue from there.

**Comment by nikr** [comment]
I am seeing this as well, with large repositories hosted on GitLab CE, using libgit2sharp 0.24.0 from NuGet.

It is occurring both on Clone and Fetch commands. 

However, unlike @AndreyVaskovskiy for me it does start transferring the repositories. It tends to get about 10 minutes in and then crashes.

**Comment by ethomson** [comment]
0.24 is quite old.  We’re preparing the 0.25 release now.  Can you try the latest 0.25 prerelease on nuget?

**Comment by nikr** [comment]
I have a feeling that the issue might come when you have too slow processing in the  TransferProgressHandler. But I will do some testing to confirm/disprove that theory when I have some time.
I'll test with 0.25 prerelease as well.

**Comment by ven0x6** [comment]
Hi, I am seeing this as well, with large repositories hosted on a private git server (with slow internet connection or local network connection limited with netlimiter app), using libgit2sharp 0.24 from source code (with NativeBinaries Nuget 1.0.185) or Nuget.

This crash happens when clone or fetch process takes too much time :
- with fast local network connection (~400 Mb/sec), there is no crash.
- with slow connection (internet or local network limited with netlimiter, ~15Mb/sec), this crash always happens with large repositories

Here is what I tried with libgit2sharp :
- update libgit2sharp to 0.25 from source code (with NativeBinaries Nuget 1.0.210) => no change
- use libgit2sharp 0.25 Nuget without proxy with slow connection => no change
- use libgit2sharp 0.25 Nuget without proxy with fast connection => suceed, no problem
- disable all ProgressHandler (OnTransferProgress, OnProgress, OnCheckoutProgress...) => no change
- clone multiple large repositories from different source with slow connection => no change
- clone large repo with fast connection => suceed, no problem

When I clone with git from console with slow connection and the same large repository, it succeeds wihtout any problem.

From what I understand, the transfer begins and crashes if the process takes too much time. The crash does not always happen after 10 min. I have the feeling that this crash occurs only if the process takes too much time but only after a certain amount of data, so the « timeout » is not always the same.

For example, if I limit the speed rate to 15Mb/sec, the crash occurs after ~10 min and if I limit the speed rate to 8Mb/sec, it occurs after 15 min.

I use libgit2sharp source code because I needed to add a custom proxy handler, but the crash happens even if I use the Nuget without the proxy.

I am seeing this for more than 1 year, and I really don't know how to fix it.

**Comment by ven0x6** [comment]
Hi, any news on the issue ?

**Comment by xiaofuhub** [comment]
Hi, I also encountered the same problem with version libgit2 2.0.26. when I use git_push(), The small application has no problem. The big application returns the request failure. When I use TortoiseGit, the upload is normal, and the memory footprint is very small. Does the performance need to be optimized?
