### ISSUE TITLE
Error when calling repo.Diff.Compare<Patch> on large changesets (4800 files in the commit)

### ISSUE THREAD

**Issue by Eibwen** [libgit2/libgit2sharp#1523]
libgit2sharp 0.25.0-preview-0073

Have a repo that the pack file is 2gb total (I mention because I can't just share this) and 3 of the commits out of it error with my current code.
I'm trying to export information so I can build statistics about the repo for fun.  The data where this error is occurring is getting all the files modified by a commit along with the LinesAdded and LinesDeleted of each.

The line that errors is `repo.Diff.Compare<Patch>(parent.Tree, commit.Tree)`

Two of the stacktraces have this error:
```
LibGit2Sharp.LibGit2SharpException: No error message has been provided by the native library
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_patch_from_diff(DiffHandle diff, Int32 idx)
   at LibGit2Sharp.Patch..ctor(DiffHandle diff)
   at LibGit2Sharp.Diff.<>c.<.cctor>b__36_0(DiffHandle diff)
   at LibGit2Sharp.Diff.BuildDiffResult[T](DiffHandle diff)
   at LibGit2Sharp.Diff.Compare[T](Tree oldTree, Tree newTree, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions, CompareOptions compareOptions)
   at LibGit2Sharp.Diff.Compare[T](Tree oldTree, Tree newTree)
```
One of these was were we refactored `node_modules` in the repo, resulting in  4885 additions and 7 deletions
The other commit was where we deleted `node_modules` from the repo, which was 4865 deletions

Is there anything I can try to the commit patch data using libgit2sharp?  And/or is there any better way to get all the files modified by a commit along with the LinesAdded and LinesDeleted of each?

Or let me know what other information I can provide to help debug this!

**Comment by Eibwen** [comment]
Whoops, it seems rerunning actually got these commits to work successfully, but I didn't realize because of how I was handling the outputs

So not sure if there was an error that I fixed, or just had an error the first time for random-ish reasons
