### ISSUE TITLE
user cancelled certificate check

### ISSUE THREAD

**Issue by nk111** [libgit2/libgit2sharp#1546]
I'm using the github for visual studio extension in VS2017. When i try to create a new pull request i always get the error message "user cancelled certificate check".

This is the log:
2018-03-13 17:35:10.332 INFO [56] GitHubPackage             Initializing GitHub Extension v2.4.3.1737 in Microsoft Visual Studio 2017 (15.6.27428.2002)
2018-03-13 17:35:32.470 EROR [12] PullRequestCreationViewModel Error creating pull request
LibGit2Sharp.LibGit2SharpException: user cancelled certificate check: 
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_push(RemoteHandle remote, IEnumerable`1 refSpecs, GitPushOptions opts)
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs, PushOptions pushOptions)
   at LibGit2Sharp.Network.Push(Remote remote, String pushRefSpec, PushOptions pushOptions)
   at LibGit2Sharp.Network.Push(Remote remote, String objectish, String destinationSpec, PushOptions pushOptions)
   at GitHub.Services.GitClient.<>c__DisplayClass7_0.<Push>b__0() in C:\projects\visualstudio\src\GitHub.App\Services\GitClient.cs:line 64
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Services.PullRequestService.<PushAndCreatePR>d__42.MoveNext() in C:\projects\visualstudio\src\GitHub.App\Services\PullRequestService.cs:line 659

Any ideas how to fix this?

**Comment by ethomson** [comment]
You'd need to add a certificate validation callback to your code.  But if you're using the GitHub for Visual Studio 2017, then you need to open an issue [in that project](https://github.com/github/visualstudio).

**Comment by nk111** [comment]
Thanks for the heads up @ethomson

**Comment by ethomson** [comment]
No problem.  Mention me on the issue if you’d like and I can give some input.

**Comment by rotemwolfovich** [comment]
Hi , 
my app was using the ibgit2sharp 0.22 version and i was able to push and clone even when i was working under  a proxy server . 
now i want to use the libgit2sharp-ssh version  but i am getting this exception ? 
is   libgit2sharp-ssh not support proxy ? or this connect to something else ? 

thank you !
