### ISSUE TITLE
Can't push all tags

### ISSUE THREAD

**Issue by splatteredbits** [libgit2/libgit2sharp#1552]
When I try to push all tags, I get this exception:

```
LibGit2Sharp.LibGit2SharpException: not a valid reference 'refs/tags/*'
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_push(RemoteHandle remote, IEnumerable`1 refSpecs, GitPushOptions opts)
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs, PushOptions pushOptions)
   at CallSite.Target(Closure , CallSite , Object , Object , Object , Object )
```

Here's my PowerShell code:

```
$pushOptions = New-Object -TypeName 'LibGit2Sharp.PushOptions'
$repo = New-Object 'LibGit2Sharp.Repository' ($RepoRoot)
$remote = $repo.Network.Remotes | Where-Object { $_.Name -eq 'origin' }
$repo.Network.Push($remote, 'refs/tags/*', $pushOptions)
```

I've also tried using `refs/tags/*:refs/tags/*` as the refspec, but that fails too. I can push individual tags with refspec `refs/tags/tag_name`.

**Comment by ethomson** [comment]
There's no wildcard support when pushing, AFAIK.  You'll need to iterate the tags yourself and push them individually.

@carlosmn can remind me if I'm correct about this.

**Comment by carlosmn** [comment]
Indeed, libgit2 does not currently support wildcards in the refspecs used for pushing.
