### ISSUE TITLE
Segmentation Fault in Alpine 3.8

### ISSUE THREAD

**Issue by thefringeninja** [libgit2/libgit2sharp#1647]
### Reproduction steps
Dockerfile:
```
FROM microsoft/dotnet:2.2.100-sdk-alpine3.8 AS build

COPY .git ./

RUN apk add libcurl &&  \
  dotnet tool install -g minver-cli --version 1.0.0-beta.1 && \
  /root/.dotnet/tools/minver > .version
```

(minver takes a dependency on libgit2sharp)
### Expected behavior
Prints the expected version

### Actual behavior
Segmentation Fault

### Version of LibGit2Sharp (release number or SHA1)
0.25.3

### Operating system(s) tested; .NET runtime tested
`microsoft/dotnet:2.2.100-sdk-alpine3.8` docker container

I tried this with the `microsoft/dotnet:2.2.100-sdk-stretch` container and it worked as expected.

**Comment by bording** [comment]
@thefringeninja Do you have any more details on the actual error that's happening here? An actual error message would be helpful!

**Comment by thefringeninja** [comment]
That's the only error message I get unfortunately. Tried GDB:
```
(gdb) run
Starting program: /root/.dotnet/tools/minver
[New LWP 463]
[New LWP 464]
[New LWP 465]
[New LWP 466]
[New LWP 467]
[New LWP 468]
[New LWP 469]

Thread 1 "minver" received signal SIGSEGV, Segmentation fault.
0x0000000000014246 in ?? ()
```

**Comment by bording** [comment]
Okay, we'll need to try using LibGit2Sharp more directly inside the container to see what's going on, then.

**Comment by adamralph** [comment]
@thefringeninja have you tried MinVer 1.0.0-beta.2 with this image? It uses LibGit2Sharp 0.26.0-preview-0070 so I'm wondering if that makes any difference.

**Comment by thefringeninja** [comment]
Yes, in fact you made the change in SQLStreamStore/SQLStreamStore.HAL#48 :)

I rebased after and force pushed but it still did not work.

**Comment by adamralph** [comment]
@thefringeninja yep, I know I made the change to beta 2, but I didn't know if you'd tried yet it with the problematic image, since your `master` is still `using microsoft/dotnet:2.1.500-sdk-alpine3.7`.

**Comment by adamralph** [comment]
@thefringeninja you mentioned that you saw a different error in Alpine 3.9?

**Comment by thefringeninja** [comment]
yes:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-572e4d8' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgit2-572e4d8: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)
   at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
   at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, RepositoryRequiredParameter requiredParameter)
   at MinVer.Lib.RepositoryEx.TryCreateRepo(String repoOrWorkDir, Repository& repository) in C:\projects\min-ver\MinVer.Lib\RepositoryEx.cs:line 16
   at MinVer.Lib.Versioner.GetVersion(String repoOrWorkDir, String tagPrefix, ILogger log) in C:\projects\min-ver\MinVer.Lib\Versioner.cs:line 30
   at MinVer.Lib.Versioner.GetVersion(String repoOrWorkDir, String tagPrefix, MajorMinor minMajorMinor, String buildMeta, ILogger log) in C:\projects\min-ver\MinVer.Lib\Versioner.cs:line 7
   at MinVer.Program.<>c__DisplayClass1_0.<Main>b__0() in C:\projects\min-ver\minver-cli\Program.cs:line 66
   at MinVer.Program.Main(String[] args) in C:\projects\min-ver\minver-cli\Program.cs:line 35
```

**Comment by bording** [comment]
I've just recently been helping Nerdbank.GitVersioning with Alpine stuff, so I believe I know what's going on here.

LibGit2Sharp 0.26.0 has an `alpine-x64` binary. When using Alpine 3.7, that binary will be chosen. However, for 3.8 or 3.9, the .NET Core SDK was missing the RID graph information required to select the proper binaries.

On top of that, Alpine 3.9 moved to OpenSSL 1.1, so the existing binary won't work since it is built against OpenSSL 1.0, which 3.7 and 3.8 use.

This weekend I added an Alpine 3.9 binary, and you can use it with LibGit2Sharp 0.27.0-preview-0007.

The required RIDs have been added to the corefx repo, but they haven't made it into a 2.2 SDK release yet. The latest 2.1 SDK does have them, however.

So, if you use LibGit2Sharp 0.27.0-preview-0007 and the 2.1.505 SDK image, I believe Alpine 3.7, 3.8 and 3.9 will work.

**Comment by adamralph** [comment]
😵

FTR I will release a version of MinVer containing LibGit2Sharp 0.27.0 as soon as it's released.

**Comment by bording** [comment]
> FTR I will release a version of MinVer containing LibGit2Sharp 0.27.0 as soon as it's released.

That's not likely to be any time soon, so you might want to consider upgrading sooner.

**Comment by adamralph** [comment]
@bording why is that latest version a preview and not RTM?

**Comment by bording** [comment]
> @bording why is that latest version a preview and not RTM?

Because that's just how the releases here tend to go, following the trend of libgit2 itself.

**Comment by adamralph** [comment]
Does that mean there is no inherent difference between preview and RTM?

**Comment by bording** [comment]
Correct, there are no code differences, just the package reference update to point to the new version of the native binaries package.

**Comment by bording** [comment]
@adamralph I could look into releasing it as a 0.26.1 if that would work better for you.

**Comment by adamralph** [comment]
@bording what would be the difference between 0.26.1 and 0.27.0-preview-0007?

I'm trying to get an idea of what the `preview-*` part signifies. My usual assumption is:

> This might not be quite as stable as an RTM so only use it if you really want/need to be cutting edge, or you want to test stuff ahead of the RTM release (but not use it in production).

**Comment by bording** [comment]
> @bording what would be the difference between 0.26.1 and 0.27.0-preview-0007?

There wouldn't be any difference. It would just be a way to not have a prerelease tag on the package.

**Comment by thefringeninja** [comment]
0.26.1 works for me

**Comment by adamralph** [comment]
@bording OK, if you could release it as 0.26.1 then I'll be happy to upgrade MinVer to that.

To clarify, it's the not the version number itself that concerns me, but rather knowing that a specific version is of RTM quality and that I can confidently upgrade to it. So I guess even if 0.26.1 vs 0.27.0-preview-0007 is effectively nothing more than a different label, it serves as a good way for you to confirm and communicate the RTM quality of the preview. I guess that's the whole idea of SemVer. 🙂

**Comment by adamralph** [comment]
@bording are you planning to release 0.26.1?

**Comment by ViceIce** [comment]
Seeing the same on `mcr.microsoft.com/dotnet/core/sdk:2.2.402-alpine` which is `alpine 3.9` now
