### ISSUE TITLE
Not seeing any branches, can't create branch

### ISSUE THREAD

**Issue by barnao** [libgit2/libgit2sharp#1658]
I am running into the following error when  try to create a branch...

```
LibGit2Sharp.NotFoundException: revspec 'master' not found
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_annotated_commit_from_revspec(RepositoryHandle repo, String revspec)
   at LibGit2Sharp.Core.Proxy.git_branch_create_from_annotated(RepositoryHandle repo, String branch_name, String targetIdentifier, Boolean force)
   at LibGit2Sharp.BranchCollection.Add(String name, String committish, Boolean allowOverwrite)
   at LibGit2Sharp.BranchCollection.Add(String name, String committish)
   at LibGit2Sharp.RepositoryExtensions.CreateBranch(IRepository repository, String branchName)
   at EncompassSettingsExport.GitWriter..ctor(String PathToRepo, Signature Signature, CredentialsHandler credentialsHandler, String Branch, String SupplimentalPath, ILogger logger, Boolean purgeDirectory) in C:\Users\barnao\Downloads\EncompassSettingsExport2\EncompassSettingsExport\EncompassSettingsExport\GitWriter.cs:line 52
   at EncompassSettingsExport.Program.<Run>d__1.MoveNext() in C:\Users\barnao\Downloads\EncompassSettingsExport2\EncompassSettingsExport\EncompassSettingsExport\Program.cs:line 71
Finished! Press any key to exit...
```

The line o code that produces this error is

`brnch = repo.CreateBranch(Branch);`

Where Branch is just a string like "test-brnch"

I am checking to make sure i can see my repo (it is a private repo not local)

`Repository.IsValid(PathToRepo)`

and this returns true.

I create my repo here

`repo = new Repository(PathToRepo);`

However when i call 

`repo.Branches.Count();`

This return 0 even though i do have a few branches in my repo

Any advice?

**Comment by VulumeCode** [comment]
This is how git works, libgit can't do anything about it. 

Master is created with the initial commit, so you can't create a branch before that. "git status" in a new repo will tell you you're on master, but if you do "git branch" you will see it's not actually there yet. 

Note that "git checkout -b [name]" does not actually create a branch until you commit on it. You can do a bunch of those without effect. If you do it on an empty repo you're just renaming what master will be. If you do "git branch [name]" you'll get the same error.
