### ISSUE TITLE
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. "Unable to load DLL 'git2-572e4d8': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by v-raras** [libgit2/libgit2sharp#1681]
We are also getting the same exception. We are using Azure Function and using v0.26.0 of LibGit2Sharp. This exception arises when we are debugging our azure function using Azure CLI debugger.
We have already tried adding 'AutoGenerateBindingRedirects true AutoGenerateBindingRedirects' to csproj file of the project but still no luck. Though it runs fine in console app but is throwing exception in Azure function.
Here is the stack trace:
at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)
at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, RepositoryRequiredParameter requiredParameter)
at LibGit2Sharp.Repository..ctor(String path)
at GitDeploy.GitRepositoryManager.UpdateRepository()
at CrmSolution.RepositoryHelper.TryPushToRepository(String committerName, String committerEmail, String authorEmail, SolutionFileInfo solutionFile, String solutionFilePath, HashSet`1 hashSet)
at CrmSolution.RepositoryHelper.TryUpdateToRepository(String solutionUniqueName, String committerName, String committerEmail, String authorEmail)

**Comment by v-raras** [comment]
@ethomson @bording can you guys please provide any lead on this as I'm really stuck here with my azure function. 
PS: I'm not getting this Lib2git exception when deployed as a webjob.

**Comment by v-raras** [comment]
Hi @ethomson  @bording it would be very helpful if you guys can spare some time to provide any lead on this just in case you know how to handle library dependency in Azure Function

**Comment by ethomson** [comment]
Sorry @v-raras, I'm not working on LibGit2Sharp anymore, and this is outside my area of expertise.  I'd encourage you to ask on StackOverflow.  This seems unique to Azure Functions or the debugger.

**Comment by rbnswartz** [comment]
@v-raras I had this problem today and I figured out how to fix it. I modified the publishing configuration to not use the Portable runtime identifier and use the win-64 runtime instead. I also set the runtime to 64 bit in the azure portal but I don't know if that had any effect on that at all.
