### ISSUE TITLE
503 - During clone 

### ISSUE THREAD

**Issue by sharpSteff** [libgit2/libgit2sharp#1682]
### Version of LibGit2Sharp (release number or SHA1)
Master -7f59d22c
### Operating system(s) tested; .NET runtime tested

I receive a "503" when trying to clone a repo from our self host git-service (gitea)

url looks like this:
`https://{server}/git/{orga}/{repo}`

cloning via git command line works without any problem:
`git clone https://mytoken@{server}/git/{orga}/{repo}`

i'm passing the token via cloneoptions.Credentialsprovider

```
 var co = new CloneOptions();
            co.CredentialsProvider = (_url, _user, _cred) =>
                new UsernamePasswordCredentials
                {
                    Username = "mytoken",
                    Password = string.Empty
                };

            string clonedRepoPath = Repository.Clone(url, scd.DirectoryPath, co);
```

Stacktrace:
LibGit2Sharp.LibGit2SharpException : request failed with status code: 503
```
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in C:\Users\stefan.kneidl\Source\Repos\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in C:\Users\stefan.kneidl\Source\Repos\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in C:\Users\stefan.kneidl\Source\Repos\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 276
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in C:\Users\stefan.kneidl\Source\Repos\libgit2sharp\LibGit2Sharp\Repository.cs:line 793
   at LibGit2Sharp.Tests.CloneFixture.CanCloneGitea(String url) in C:\Users\stefan.kneidl\Source\Repos\libgit2sharp\LibGit2Sharp.Tests\CloneFixture.cs:line 55
```

As additional information when trying to access the git server via browser:
`https://{myserver}/git` 
returns: The service is not available. Please try again later.
`https://{myserver}/git/` works as intended

**Comment by lstefano71** [comment]
As far as I know, the token should go in the Password and the User field should contain the user which created the token. It certainly works for me that way...

**Comment by sharpSteff** [comment]
in #1256 they mentioned it the other way arround.

However I tried your idea, but doesnt work for me. Still 503

**Comment by sharpSteff** [comment]
found out we have a reverse proxy.
