### ISSUE TITLE
SSL error on clone when running in .NET core 3.0 on Alpine Linux

### ISSUE THREAD

**Issue by liiri** [libgit2/libgit2sharp#1731]
I'm running the following code:

```
var cloneOptions = new CloneOptions
{
    CredentialsProvider = ...,
    CertificateCheck = (certificate, valid, host) => true;
}
LibGit2Sharp.Repository.Clone(
    "url",
    "targetPath",
    cloneOptions
);
```

Using `LibGit2Sharp 0.27.0.0` with `git2-7ce88e6.dll`

![img](https://i.imgur.com/YcdTfXd.png)

Whereas my git server is hosted on a remote server and I access it via IP address on https. I would like to trust the certificate.

The code works fine for when I'm running in my dev environment (OSX), but fails in my runtime, which is run on `mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine` docker image.

Error trace:

```
LibGit2Sharp.LibGit2SharpException: SSL error: received early EOF
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
```

I'm guessing this is OS-specific in some manner. Any advice?

It might be the same issue as https://github.com/libgit2/libgit2sharp/issues/1262

**Comment by liiri** [comment]
After digging around this seems to actually be relevant only to the native implementation. Opened an issue there: https://github.com/libgit2/libgit2/issues/5279
