### ISSUE TITLE
Unstable tests based on AssertRefLogEntry

### ISSUE THREAD

**Issue by AArnott** [libgit2/libgit2sharp#1764]
Several tests are unstable and fail all too frequently on CI and perhaps locally.

From [this run](https://github.com/AArnott/libgit2sharp/runs/418614588?check_suite_focus=true) of [this commit](https://github.com/AArnott/libgit2sharp/commit/075cac52c3297fc869a17f0c84f70834a73f920f) the windows agent happened to fail with this log: 

```
  X LibGit2Sharp.Tests.BranchFixture.CanCreateBranchFromCommit [63ms]
  Error Message:
   Assert.InRange() Failure
Range:  (1/31/2020 4:54:25 AM +00:00 - 1/31/2020 4:54:25 AM +00:00)
Actual: 1/31/2020 4:54:24 AM +00:00
  Stack Trace:
     at LibGit2Sharp.Tests.TestHelpers.BaseFixture.AssertRefLogEntry(IRepository repo, String canonicalName, String message, ObjectId from, ObjectId to, Identity committer, DateTimeOffset before) in D:\a\libgit2sharp\libgit2sharp\LibGit2Sharp.Tests\TestHelpers\BaseFixture.cs:line 471
   at LibGit2Sharp.Tests.BranchFixture.CanCreateBranchFromCommit() in D:\a\libgit2sharp\libgit2sharp\LibGit2Sharp.Tests\BranchFixture.cs:line 205
```

It looks to me like the `before` local variable is still set to a later value than is recorded in the commit at times, for whatever reason.

**Comment by AArnott** [comment]
I see a bunch of tests that use 

```cs
var before = DateTimeOffset.Now.TruncateMilliseconds();
```

As a marker. Should they all be updated to subtract one second? Or should we update `AssertRefLogEntry` to deduct one second from the `before` arg passed in?

**Comment by AArnott** [comment]
Case in point: another agent from that same commit [failed another test](https://dev.azure.com/libgit2sharp/libgit2sharp/_build/results?buildId=253&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3d94a178-cdfb-5c90-a971-5deeccbbe043&l=81) with exactly the same pattern.

```
  X LibGit2Sharp.Tests.BranchFixture.CanCreateBranchUsingAbbreviatedSha [77ms]
  Error Message:
   Assert.InRange() Failure
Range:  (1/31/2020 4:57:07 AM +00:00 - 1/31/2020 4:57:07 AM +00:00)
Actual: 1/31/2020 4:57:06 AM +00:00
  Stack Trace:
     at LibGit2Sharp.Tests.TestHelpers.BaseFixture.AssertRefLogEntry(IRepository repo, String canonicalName, String message, ObjectId from, ObjectId to, Identity committer, DateTimeOffset before) in D:\a\1\s\LibGit2Sharp.Tests\TestHelpers\BaseFixture.cs:line 471
   at LibGit2Sharp.Tests.BranchFixture.CanCreateBranchUsingAbbreviatedSha() in D:\a\1\s\LibGit2Sharp.Tests\BranchFixture.cs:line 119
```

**Comment by bording** [comment]
I was looking at that tonight, and thought #1762 might be a fix, but it looks like the range in the assert isn't the problem. Despite capturing the `before` value before test operation, sometimes the operation has a value that is earlier.

While we could just make the tests pass by opening up the range, I'm not sure that's the right thing to do. Seems like this could actually be a legit problem in how those values are being calculated.

**Comment by AArnott** [comment]
> Seems like this could actually be a legit problem in how those values are being calculated.

Well, I guess I'll let you decide the fate of my PR that I just filed. But unstable tests cost a lot, so my little vote would be, accept my PR and leave this bug open to track investigating the underlying product failure if you want to. 
But IMHO, no one will care about half a second rounding error like that. We've got bigger issues to spend time on... like #1618. :)

**Comment by bording** [comment]
>  But unstable tests cost a lot, so my little vote would be, accept my PR and leave this bug open to track investigating the underlying product failure if you want to.

Seems like a pragmatic way to move forward. Let's see if the PR is green, and if so I'll merge it.

**Comment by bording** [comment]
Reopening the issue so we can keep it around to investigate why #1765 was needed as a workaround.
