### ISSUE TITLE
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. STACKTRACE:    at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)

### ISSUE THREAD

**Issue by shubhamgoel-tomhorn** [libgit2/libgit2sharp#1839]
I am trying to run this on linux using dotnet core. Will it work on dotnet core. I am getting the following error while cloning repo in linux 

The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. STACKTRACE:    at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)
   at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
   at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, RepositoryRequiredParameter requiredParameter)

**Comment by ivan-penchev-maersk** [comment]
I am getting the same Error, running on Azure Devops with latest ubuntu image as a build.

This is the full trace

```charp

---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: lib/linux-x64/libgit2-106a5f2.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
  at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary () [0x00002] in <c6ddab362adb4977b9e6460e3b7d98f1>:0 
  at LibGit2Sharp.Core.NativeMethods..cctor () [0x00045] in <c6ddab362adb4977b9e6460e3b7d98f1>:0 
   --- End of inner exception stack trace ---
  at LibGit2Sharp.Core.Proxy.git_repository_open (System.String path) [0x00008] in <c6ddab362adb4977b9e6460e3b7d98f1>:0 
  at LibGit2Sharp.Repository..ctor (System.String path, LibGit2Sharp.RepositoryOptions options, LibGit2Sharp.Repository+RepositoryRequiredParameter requiredParameter) [0x002fa] in <c6ddab362adb4977b9e6460e3b7d98f1>:0 
  at LibGit2Sharp.Repository..ctor (System.String path) [0x00000] in <c6ddab362adb4977b9e6460e3b7d98f1>:0 
  at Cake.Git.Extensions.RepositoryExtensions.UseRepository[TResult] (Cake.Core.ICakeContext context, Cake.Core.IO.DirectoryPath repositoryPath, System.Func`2[T,TResult] repositoryFunc) [0x0007c] in <311bafd9d79544c881b3dd60e16845b6>:0 
  at Cake.Git.GitAliases.GitLogTip (Cake.Core.ICakeContext context, Cake.Core.IO.DirectoryPath repositoryDirectoryPath) [0x00029] in <311bafd9d79544c881b3dd60e16845b6>:0 
  at Submission#0.GitLogTip (Cake.Core.IO.DirectoryPath repositoryDirectoryPath) [0x0000c] in <3ac4ac5b7c0d4e228b33b9753e1c2d9c>:0 
  at Submission#0.<<Initialize>>b__0_1 () [0x0001e] in <3ac4ac5b7c0d4e228b33b9753e1c2d9c>:0 
  at Cake.Core.CakeTaskBuilderExtensions+<>c__DisplayClass29_0.<Does>b__0 (Cake.Core.ICakeContext context) [0x00000] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.CakeTaskBuilderExtensions+<>c__DisplayClass32_0.<Does>b__0 (Cake.Core.ICakeContext x) [0x00000] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.CakeTask.Execute (Cake.Core.ICakeContext context) [0x0006c] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.DefaultExecutionStrategy.ExecuteAsync (Cake.Core.CakeTask task, Cake.Core.ICakeContext context) [0x000ee] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.CakeEngine.ExecuteTaskAsync (Cake.Core.ICakeContext context, Cake.Core.IExecutionStrategy strategy, System.Diagnostics.Stopwatch stopWatch, Cake.Core.CakeTask task, Cake.Core.CakeReport report) [0x000de] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.CakeEngine.ExecuteTaskAsync (Cake.Core.ICakeContext context, Cake.Core.IExecutionStrategy strategy, System.Diagnostics.Stopwatch stopWatch, Cake.Core.CakeTask task, Cake.Core.CakeReport report) [0x00270] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.CakeEngine.ExecuteTaskAsync (Cake.Core.ICakeContext context, Cake.Core.IExecutionStrategy strategy, System.Diagnostics.Stopwatch stopWatch, Cake.Core.CakeTask task, Cake.Core.CakeReport report) [0x00354] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.CakeEngine.RunTask (Cake.Core.ICakeContext context, Cake.Core.IExecutionStrategy strategy, Cake.Core.CakeTask task, System.String target, System.Diagnostics.Stopwatch stopWatch, Cake.Core.CakeReport report) [0x00124] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Core.CakeEngine.RunTargetAsync (Cake.Core.ICakeContext context, Cake.Core.IExecutionStrategy strategy, Cake.Core.ExecutionSettings settings) [0x00338] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Cake.Cli.BuildScriptHost`1[TContext].RunTargetAsync (System.String target) [0x0009d] in <f7c6eda5093d42ae87d44bab4f23d082>:0 
  at Cake.Core.Scripting.ScriptHost.RunTarget (System.String target) [0x0000d] in <d3b050afcd80473f8f6f779ce234e691>:0 
  at Submission#0+<<Initialize>>d__0.MoveNext () [0x0041b] in <3ac4ac5b7c0d4e228b33b9753e1c2d9c>:0 
  at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult] (System.Collections.Immutable.ImmutableArray`1[T] precedingExecutors, System.Func`2[T,TResult] currentExecutor, System.Runtime.CompilerServices.StrongBox`1[T] exceptionHolderOpt, System.Func`2[T,TResult] catchExceptionOpt, System.Threading.CancellationToken cancellationToken) [0x00186] in <ac455dd50d88471c92708b521d33863b>:0 
  at Microsoft.CodeAnalysis.Scripting.Script`1[T].RunSubmissionsAsync (Microsoft.CodeAnalysis.Scripting.ScriptExecutionState executionState, System.Collections.Immutable.ImmutableArray`1[T] precedingExecutors, System.Func`2[T,TResult] currentExecutor, System.Func`2[T,TResult] catchExceptionOpt, System.Threading.CancellationToken cancellationToken) [0x000ab] in <ac455dd50d88471c92708b521d33863b>:0 <---

```

The only thing we do is, we call ```charp var logTip = GitLogTip("./"); var shortSha = logTip.Sha.Substring(0, 8);```
This pipeline worked till today without an issue? Updating to 1.0.0 of Git.Cake did not help.

We are running .NET Core 3.1 service build on it.

Addins are only added inline, and all the addins we have are
```
#tool "nuget:?package=Microsoft.TestPlatform&version=16.8.3"
#addin nuget:?package=Cake.Git&version=1.0.0
#addin nuget:?package=Cake.Http&version=0.7.0
#addin nuget:?package=Cake.Json&version=5.2.0
#addin nuget:?package=Newtonsoft.Json&version=11.0.2

```

**Comment by lprichar** [comment]
Any updates on this?  I've just gotten this after intentionally updating to Ubuntu 20.  Going back to 18 is not an option.

**Comment by bording** [comment]
It should work if you use the latest prerelease version.

**Comment by lprichar** [comment]
@bording What is the latest prerelease version or how do I get it?  I'm only seeing v1.01 in nuget, which is what I'm on and isn't prerelease.

**Comment by bording** [comment]
> @bording What is the latest prerelease version or how do I get it? I'm only seeing v1.01 in nuget, which is what I'm on and isn't prerelease.

What exact package name are you looking at? LibGit2Sharp doesn't have a 1.0 version at all:

https://www.nuget.org/packages/LibGit2Sharp

The latest prerelease version is 0.27.0-preview-0102.

**Comment by lprichar** [comment]
Oh, I'm an idiot, I'm using a downstream app (https://github.com/cake-contrib/Cake_Git) that has a dependency on an older version of libgit2sharp.  My product even has an outstanding PR to update to 0.27.0-preview-0102 from a few days ago.  Perfect, thank you @bording for your help!

**Comment by bording** [comment]
Since this should be fixed in the latest preview versions, I'm going to close the issue.
