### ISSUE TITLE
 LibGit2SharpException: unknown style 'zdiff3' given for 'merge.conflictstyle'

### ISSUE THREAD

**Issue by vchirikov** [libgit2/libgit2sharp#1976]
### Reproduction steps

set in gitconfig merge.conflictstyle to zdiff3

### Expected behavior

Working libgit2sharp

### Actual behavior

```
LibGit2Sharp.LibGit2SharpException: unknown style 'zdiff3' given for 'merge.conflictstyle'
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutOpts& opts)
   at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts)
   at LibGit2Sharp.Repository.Checkout(Tree tree, IEnumerable`1 paths, CheckoutOptions options)
   at LibGit2Sharp.Commands.Checkout(IRepository repository, Tree tree, CheckoutOptions checkoutOptions, String refLogHeadSpec)
   at LibGit2Sharp.Commands.Checkout(IRepository repository, Branch branch, CheckoutOptions options)
   at LibGit2Sharp.Commands.Checkout(IRepository repository, Branch branch)
   at Nerdbank.GitVersioning.ReleaseManager.PrepareRelease(String projectDirectory, String releaseUnstableTag, Version nextVersion, Nullable`1 versionIncrement, ReleaseManagerOutputMode outputMode) in D:\a\1\s\src\NerdBank.GitVersioning\ReleaseManager.cs:line 285
   at Nerdbank.GitVersioning.Tool.Program.OnPrepareReleaseCommand(String project, String nextVersion, String versionIncrement, String format, String tag) in D:\a\1\s\src\nbgv\Program.cs:line 736
   --- End of inner exception stack trace ---
```

### Version of LibGit2Sharp (release number or SHA1)

0.27.0-preview-0182

### Operating system(s) tested; .NET runtime tested

Windows / dotnet 6.0.5

**Comment by VulumeCode** [comment]
Reproduced here. Zdiff3 is available since git 2.35, January 2022.
