### ISSUE TITLE
Can't access GIT config (Repository.Config) since v0.27.0

### ISSUE THREAD

**Issue by ozanneconsulting** [libgit2/libgit2sharp#2031]
### Reproduction steps
Open an existing repository: 
Repository localRepository = new Repository(localPath);

Access localRepository.Config

### Expected behavior
Repository.Config gives access to GIT configuration

### Actual behavior
Any access of Repository.Config throws an exception:

the ProgramData file 'config' doesn't exist:
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever) in /_/LibGit2Sharp/Core/Proxy.cs:line 3801
   at LibGit2Sharp.Configuration..ctor(Repository repository, String repositoryConfigurationFileLocation, String globalConfigurationFileLocation, String xdgConfigurationFileLocation, String systemConfigurationFileLocation) in /_/LibGit2Sharp/Configuration.cs:line 46
   at LibGit2Sharp.Repository.<>c__DisplayClass25_1.<.ctor>b__3() in /_/LibGit2Sharp/Repository.cs:line 220
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()

### Version of LibGit2Sharp (release number or SHA1)
0.27.0 et 0.27.1 (it works fine in 0.26.2

### Operating system(s) tested; .NET runtime tested
Windows 11, .NET 6.0, console application.

**Comment by ozanneconsulting** [comment]
This is a duplicate of #2021

**Comment by bording** [comment]
@ozanneconsulting This is actually a slightly different scenario than #2021, so I'm reopening it. #2021 is talking about the behavior when using the default constructor, and your issue is about when you've passed a path to an actual repo.

**Comment by arturcic** [comment]
@bording can we have a new release ?

**Comment by bording** [comment]
Fixed in LibGit2Sharp [v0.27.2](https://www.nuget.org/packages/LibGit2Sharp/0.27.2).

**Comment by ozanneconsulting** [comment]
@bording I confirm this release fixes my problem.
Thanks for your unbelievable reactivity.

**Comment by ethomson** [comment]
Glad to hear it. Seconding my thanks to @bording. 🎉
