### ISSUE TITLE
LibGit2Sharp.LibGit2SharpException | too many redirects or authentication replays

### ISSUE THREAD

**Issue by belkhir-aziz** [libgit2/libgit2sharp#2117]
I am using LibGit2Sharp (version 0.28.0) with a Personal Access Token for authentication in the FetchOptions:

$"Authorization: Basic {Convert.ToBase64String(Encoding.UTF8.GetBytes($":{credentials.PersonalAccessToken}"))}"

**Everything was working as expected until last week, when I started encountering exceptions while trying to interact with the remote repository (e.g., clone, pull, push).**

_Clone failed. | LibGit2Sharp.LibGit2SharpException | too many redirects or authentication replays
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 824_

**Comment by ethomson** [comment]
Did you upgrade anything locally (in other words, change the version of LibGit2Sharp) in the last week? If not, something has changed in Azure Repos.

You're using two authentication methods - first, you're setting `UsernamePasswordCredentials`, second you're adding _your own_ credentials in the `CustomHeader`. I would imagine that a remote host would be confused about this. What happens if you only use _one_ of these mechanisms?

**Comment by belkhir-aziz** [comment]
Thank you for your reply.
No, I haven't changed the version.
It's just that authentication with PAT doesn't work for (push, pull...), I updated the PAT to make sure it's valid.
Using DefaultCredentials() does not give any error.
Everything was ok previous week.
