### ISSUE TITLE
Fetch is taking very long and somehow the decrypted message can't be read

### ISSUE THREAD

**Issue by schmeling65** [libgit2/libgit2sharp#2137]
### Reproduction steps
- Get a repo with a size of >3GB, or even 800MB in our case yesterday was already enough (including .git-folder)
- Implement a fetch on that repo
- See how long it is taking any in some cases how it fails

Alternative way:
1. Get the [S5Updater](https://github.com/mcb5637/S5Updater/tree/master).
2. Extract it into an empty folder.
3. Start it (It will ask you if you really want to use it).
4. Set a path for the Gold-Folder (empty).
5.  Remove the checkmark of "easy mode" or "einfacher Modus" at the bottom.
6.  Press "Update MP Maps" (third button on the left.
7. Optional: check the "show log" if you wanna see our custom output with this error.
8. Read what the log is telling you.
9. Afterwards you can delete it and the folder you created for the gold-path again.

Content of the full log as file 
[message(1).txt](https://github.com/user-attachments/files/18266273/message.1.txt)

### Expected behavior
Going through and not failing after some minutes (5+ minutes)

### Actual behavior
```
LibGit2Sharp.LibGit2SharpException: could not decrypt tls message
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage) in /_/LibGit2Sharp/Core/Proxy.cs:line 2289
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in /_/LibGit2Sharp/Commands/Fetch.cs:line 79
   at S5Updater2.TaskUpdateMPMaps.FetchRepo(ReportProgressDel r, Repository rep) in C:\Users\Name\source\repos\s5\S5Updater\S5Updater2\TaskUpdateMPMaps.cs:line 357
   at S5Updater2.TaskUpdateMPMaps.HandleRepo(String repo, String branch, String url, ReportProgressDel r) in C:\Users\Name\source\repos\s5\S5Updater\S5Updater2\TaskUpdateMPMaps.cs:line 283
```
For Reference: The S5Updater is our tool where we are using Libgit2sharp to get the content we need for our Systems. There you can see that.

It is also not happening for everyone. It could be related to the speed of the internet connection. The worse the internet is, the more likely you/we are getting a failure.

One of the needed repositories is this one: https://github.com/GhoulMadness/Balancing-Stuff

Another issue was already open, but it never got discussed https://github.com/libgit2/libgit2sharp/issues/2089

### Version of LibGit2Sharp (release number or SHA1)
- 0.26.2.97 on .Net 4.8
- 0.31.0 on .Net 8.0

### Operating system(s) tested; .NET runtime tested
- Windows 10/11
- .Net runtime(s) 4.8 and 8.0

**Comment by wesdevpro-ssb** [comment]
This is still an issue for me. An update on this?

**Comment by schmeling65** [comment]
It looks like we fixed it by not downloading the whole history.
Usually when you download the files + the whole git-history, meaning all changes. So if there made many changes over the time, ALL these changes would taken into account which leads to very long fetch times.

Reducing the Steps to like 1 or 2, which just gets the normal files + maybe one or two changes, reduces the amount of time significantly

**Comment by wesdevpro-ssb** [comment]
Following a manual approach to setting up the repos and adding the long paths seemed then manually fetching them seemed to help.

I am not sure of any way to split of the fetch though. Any recommendations?
