### ISSUE TITLE
Failed to rename lockfile

### ISSUE THREAD

**Issue by dahlbyk** [libgit2/libgit2sharp#367]
When running tests I frequently get errors like this:
```
LibGit2Sharp.LibGit2SharpException : An error was raised by libgit2. Category = Os (Error).
Failed to rename lockfile to 'C:/Dev/.../TestRepos/1d117f01/.git/config': Access is denied.
```

Is anyone else seeing this, or is it just me? It seems like it started when I moved to Windows 8, but I've confirmed that virus scan and the search indexer aren't scanning `C:\Dev`. Not sure what else to check.

**Comment by JakeGinnivan** [comment]
I just got this exception from 0.22-pre but with a different exception:

```
LibGit2Sharp.LibGit2SharpException : Failed to rename lockfile to 'C:/Users/appveyor/AppData/Local/Temp/1/18eaff1a-2f66-465c-a6f0-0483592c5dc3/18eaff1a-2f66-465c-a6f0-0483592c5dc3/assembly/dl3/7d56edc2/e22e4b86_65edd001/TestRepositories/377b9b78-dc54-4f8c-bf58-687d2a46618f/.git/objects/57/e7289f72fc7261d132b1f5c91291dd31108b08': The data area passed to a system call is too small.\r\n
      Stack Trace:
         c:\projects\libgit2sharp\LibGit2Sharp\Core\Ensure.cs(160,0): at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
         c:\projects\libgit2sharp\LibGit2Sharp\Repository.cs(2011,0): at LibGit2Sharp.Repository.AddToIndex(String relativePath)
         c:\projects\libgit2sharp\LibGit2Sharp\Repository.cs(1757,0): at LibGit2Sharp.Repository.Stage(IEnumerable`1 paths, StageOptions stageOptions)
         c:\projects\libgit2sharp\LibGit2Sharp\Repository.cs(1689,0): at LibGit2Sharp.Repository.Stage(String path, StageOptions stageOptions)
```

Assume it is because of long paths?

**Comment by carlosmn** [comment]
Since we have support for retries and it's an old issue, I'm going to close. The issue @JakeGinnivan mentions is an unrelated one, seemingly due to a too-long path.
