### ISSUE TITLE
LibGit2Sharp.LibGit2SharpException: An error was raised by libgit2. Category = Unknown (Error). No error message has been provided by the native library

### ISSUE THREAD

**Issue by FallenGameR** [libgit2/libgit2sharp#789]
We have LibGit2Sharp.Index.Stage(IEnumerable) failing with:

```
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in e:\github\Libgit2sharp\libgit2sharp\LibGit2Sharp\Core\Ensure.cs:line 77
   at LibGit2Sharp.Core.Proxy.git_diff_index_to_workdir(RepositorySafeHandle repo, IndexSafeHandle index, GitDiffOptions options) in e:\github\Libgit2sharp\libgit2sharp\LibGit2Sharp\Core\Proxy.cs:line 601
   at LibGit2Sharp.Diff.BuildTreeChangesFromComparer(ObjectId oldTreeId, ObjectId newTreeId, TreeComparisonHandleRetriever comparisonHandleRetriever, DiffModifiers diffOptions, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions, CompareOptions compareOptions) in e:\github\Libgit2sharp\libgit2sharp\LibGit2Sharp\Diff.cs:line 267
   at LibGit2Sharp.Diff.Compare(DiffModifiers diffOptions, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions, CompareOptions compareOptions) in e:\github\Libgit2sharp\libgit2sharp\LibGit2Sharp\Diff.cs:line 206
   at LibGit2Sharp.Index.Stage(IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions) in e:\github\Libgit2sharp\libgit2sharp\LibGit2Sharp\Index.cs:line 162
   at GitSD.Core.GitOperator.StageFiles(String rootDir, IEnumerable`1 files) in f:\src\gitsd\1\GitSDSrc\GitSD.Core\GitOperator.cs:line 175
   at GitSD.Ext.SD.SyncAction.SyncFromSourceDepot(IEnumerable`1 changes, SDClient sdclient, String rootDir) in f:\src\gitsd\1\GitSDSrc\git-sd\SyncAction.cs:line 130
   at GitSD.Ext.SD.SyncAction.SyncChangelistsFromSD(IEnumerable`1 changesToSync, Int32 squashSize, SDClient sdclient) in f:\src\gitsd\1\GitSDSrc\git-sd\SyncAction.cs:line 82
   at GitSD.Ext.SD.SyncAction.Execute(GitSDExtArgumentObject argObj) in f:\src\gitsd\1\GitSDSrc\git-sd\SyncAction.cs:line 40
   at GitSD.Ext.SD.Program.Main(String[] args) in f:\src\gitsd\1\GitSDSrc\git-sd\Program.cs:line 34
```

There are 23 files staged, nothing fancy:

```
» git st -s -uall
 M ../../../../../build/corext/corext.config
 M ../../../../ServiceMap/AutopilotServiceMap.ini
 M ../../../../Services/net/dirs.proj
?? ../../../../Services/net/Everflow/EFCollector/EFCollector.cpp
?? ../../../../Services/net/Everflow/EFCollector/EFCollector.vcxproj
?? ../../../../Services/net/Everflow/EFCollector/EFCollectorConfig.cpp
?? ../../../../Services/net/Everflow/EFCollector/EFCollectorConfig.h
?? ../../../../Services/net/Everflow/EFCollector/EFCollectorConfig.ini
?? ../../../../Services/net/Everflow/EFCollector/EFCollectorHelper.cpp
?? ../../../../Services/net/Everflow/EFCollector/EFCollectorHelper.h
?? ../../../../Services/net/Everflow/EFCollector/EFUtils.cpp
?? ../../../../Services/net/Everflow/EFCollector/EFUtils.h
?? ../../../../Services/net/Everflow/EFCollector/FileLog.cpp
?? ../../../../Services/net/Everflow/EFCollector/FileLog.h
?? ../../../../Services/net/Everflow/EFCollector/HeaderParser.cpp
?? ../../../../Services/net/Everflow/EFCollector/HeaderParser.h
?? ../../../../Services/net/Everflow/EFCollector/PacketLogger.cpp
?? ../../../../Services/net/Everflow/EFCollector/PacketLogger.h
?? ../../../../Services/net/Everflow/EFCollector/PcapHandle.cpp
?? ../../../../Services/net/Everflow/EFCollector/PcapHandle.h
?? ../../../../Services/net/Everflow/EFCollector/sources.dep
?? ../../../../Services/net/Everflow/EFCollector/start.bat
?? ../../../../Services/net/Everflow/dirs.proj
```

We found a workaround. If Stage(string) is used to stage files one-by-one, all is working fine.

**Comment by porohkun** [comment]
have the same exception
