### ISSUE TITLE
Exception when pushing to remote

### ISSUE THREAD

**Issue by kjnilsson** [libgit2/libgit2sharp#824]
I am getting the following exception when pushing to a running git daemon (with receive-pack enabled). the exception only occurs when the daemon is running on a separate machine, not when I run the deamon on the same machine as I am pushing to.

LibGit2Sharp.LibGit2SharpException: Error receiving socket data: An existing connection was forcibly closed by the remote host.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_push_finish(PushSafeHandle push)
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs, PushOptions pushOptions, Signature signature, String logMessage)
   at LibGit2Sharp.Network.Push(Remote remote, String pushRefSpec, PushOptions pushOptions, Signature signature, String logMessage)
   at LibGit2Sharp.NetworkExtensions.Push(Network network, IEnumerable`1 branches, PushOptions pushOptions)

the git daemon is run using this command: git daemon --base-path=. --enable=receive-pack --export-all --verbose

**Comment by deanshub** [comment]
I'm having the same issue though it seems that the actual push was received...

**Comment by DomZZ** [comment]
Hello, I have the same issue :(, in my case I run an internal tool that use LibGit2Sharp in a Teamcity Agent (which is a Windows Service).

`14:04:42   Unhandled exception. LibGit2Sharp.LibGit2SharpException: error receiving data from socket: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
14:04:42   
14:04:42      at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
14:04:42      at LibGit2Sharp.Core.Proxy.git_remote_connect(RemoteHandle remote, GitDirection direction, GitRemoteCallbacks& remoteCallbacks, GitProxyOptions& proxyOptions) in /_/LibGit2Sharp/Core/Proxy.cs:line 2172
14:04:42      at LibGit2Sharp.Repository.ListRemoteReferences(String url, CredentialsHandler credentialsProvider, ProxyOptions proxyOptions) in /_/LibGit2Sharp/Repository.cs:line 721
14:04:42      at ConfigApi.Services.GitLibSharpService.Clone(String repositoryPath, String repositoryUrl, String defaultBranchName)
14:04:42      at ConfigApi.Services.FusionService.MergeGITSourceBranchToTargetBranch(IGitLibSharpService gitLibSharpService, IBitbucketApiService bitbucketApiService, String targetRepositoryPath, Boolean isAutoMode, String localBranchName)
14:04:42      at ConfigApi.Services.FusionService.FusionAsync(FusionCommandSettings fusionCommandSettings, String fusionKey, ConsoleOutputMultiplexer logger, String sourceTenantName, String sourceJsonFilePath, String tempTenantName, String targetTenantName, Boolean isAutoMode, Boolean rollback, Boolean bypassOpenedPRCheck, Boolean bypassConfigObjectExtract, CancellationToken cancellationToken)
14:04:42      at ConfigApi.Program.<>c__DisplayClass0_1.<<Main>b__14>d.MoveNext()
14:04:42   --- End of stack trace from previous location ---
14:04:42      at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
14:04:42      at ConfigApi.Program.Main(String[] args)
14:04:42      at ConfigApi.Program.<Main>(String[] args)`

If I run the tool on command line it works ...

Since the issue is still open after 11 years, I fear that it will never resolved :(

**Comment by Mattwmaster58** [comment]
In our case, we suspect this was due to not running git gc ever (only ever interacted with libgit2) in our simple git mirroring scenario. It took a year for the cruft to build up and we suspect that this caused unusually long times to build push deltas. This increased in frequency (as you'd expect) until we recloned the mirror setup providing a fresh slate for the git object database.

If this was really the cause, I think it's definitely a libgit2 bug - but we're still not sure.
