### ISSUE TITLE
ASP MVC / API Project System.TypeInitializationException was unhandled After Deployment

### ISSUE THREAD

**Issue by BoasE** [libgit2/libgit2sharp#833]
Hi 

after deploying my application to a webserver i got the following exception.

What does that mean?

On the same server i've an other application which works well.
I added lib git to the ASP MVC Start application via nuget (v. 0.17.0.0)

Any advice welcome

The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
   at LibGit2Sharp.Core.NativeMethods.git_clone(RepositorySafeHandle& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)

**Comment by nulltoken** [comment]
@ethomson @phkelley Does the class loader needs specific perms beside read?
