### ISSUE TITLE
Unexpected error on Fetch : parent is not a directory : Could not remove directory

### ISSUE THREAD

**Issue by zjrunner** [libgit2/libgit2sharp#846]
--a-- W32i   DLL   -        0.17.0.0 shp    302,080 07-07-2014 libgit2sharp.dll

2014-10-15 11:38:27,776 ERROR [GitClient] Unexpected error
LibGit2Sharp.LibGit2SharpException: Could not remove directory. File 'd:/dbs/el/dom/.git/refs/remotes/origin/personal/redacteduser/verifier/traceconv' parent is not directory: The system cannot find the path specified.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, Signature signature, String logMessage)
   at LibGit2Sharp.Network.DoFetch(RemoteSafeHandle remoteHandle, FetchOptions options, Signature signature, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, Signature signature, String logMessage)
   at DBS.Tools.GitClient.Fetch()
   at DBS.Tools.GitClient.Run(String[] args)

GitClient is our custom client using LibGit2Sharp 0.17.0.0.  These machines only use git to fetch, never making local commits.  Ideally it could handle this case across fetch to not fail and force us to remove and re-clone.

**Comment by carlosmn** [comment]
Lacking any other updates from the OP I have to conclude that it comes down to the diagnosis we made above. While a better message might be nice, it's not a bug but an effect of Git's reference namespacing semantics.
